/* Generated By:JavaCC: Do not edit this line. HistoryParserConstants.java */
package org.genedb.web.mvc.history.commandline;

public interface HistoryParserConstants {

  int EOF = 0;
  int EOL = 2;
  int UNION = 3;
  int INTERSECT = 4;
  int TIMES = 5;
  int DIVIDE = 6;
  int OPEN_PAR = 7;
  int CLOSE_PAR = 8;
  int PREVIOUS = 9;
  int NUMBER = 10;
  int DIGITS = 11;
  int DIGIT = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"UNION\"",
    "\"INTERSECT\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "<NUMBER>",
    "<DIGITS>",
    "<DIGIT>",
  };

}
