package org.gmod.schema.phylogeny;
// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7


import org.genedb.db.propinterface.PropertyI;

import org.gmod.schema.cv.CvTerm;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PhylonodeProp generated by hbm2java
 */
@Entity
@Table(name="phylonodeprop"
    ,schema="public"
    , uniqueConstraints = { @UniqueConstraint( columnNames = { "phylonode_id", "type_id", "value", "rank" } ) }
)
public class PhylonodeProp  implements java.io.Serializable, PropertyI {

    // Fields    

     private int phylonodePropId;
     private CvTerm cvTerm;
     private Phylonode phylonode;
     private String value;
     private int rank;

     // Constructors

    /** default constructor */
    public PhylonodeProp() {
    }

    /** full constructor */
    public PhylonodeProp(int phylonodePropId, CvTerm cvTerm, Phylonode phylonode, String value, int rank) {
       this.phylonodePropId = phylonodePropId;
       this.cvTerm = cvTerm;
       this.phylonode = phylonode;
       this.value = value;
       this.rank = rank;
    }
   
    // Property accessors
     @Id
    
    @Column(name="phylonodeprop_id", unique=true, nullable=false, insertable=true, updatable=true)
    public int getPhylonodePropId() {
        return this.phylonodePropId;
    }
    
    public void setPhylonodePropId(int phylonodePropId) {
        this.phylonodePropId = phylonodePropId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="type_id", unique=false, nullable=false, insertable=true, updatable=true)
    public CvTerm getCvTerm() {
        return this.cvTerm;
    }
    
    public void setCvTerm(CvTerm cvTerm) {
        this.cvTerm = cvTerm;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="phylonode_id", unique=false, nullable=false, insertable=true, updatable=true)
    public Phylonode getPhylonode() {
        return this.phylonode;
    }
    
    public void setPhylonode(Phylonode phylonode) {
        this.phylonode = phylonode;
    }
    
    @Column(name="value", unique=false, nullable=false, insertable=true, updatable=true)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="rank", unique=false, nullable=false, insertable=true, updatable=true)
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


