package org.gmod.schema.phylogeny;
// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7


import org.gmod.schema.cv.CvTerm;
import org.gmod.schema.general.DbXRef;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phylotree generated by hbm2java
 */
@Entity
@Table(name="phylotree", uniqueConstraints = {  })
public class Phylotree  implements java.io.Serializable {

    // Fields    

     private int phylotreeId;
     private CvTerm cvTerm;
     private DbXRef dbXRef;
     private String name;
     private String comment;
     private Set<Phylonode> phylonodes = new HashSet<Phylonode>(0);
     private Set<PhylotreePub> phylotreePubs = new HashSet<PhylotreePub>(0);

     // Constructors

    /** default constructor */
    public Phylotree() {
    }

	/** minimal constructor */
    public Phylotree(DbXRef dbXRef) {
        this.dbXRef = dbXRef;
    }
    /** full constructor */
    public Phylotree(CvTerm cvTerm, DbXRef dbXRef, String name, String comment, Set<Phylonode> phylonodes, Set<PhylotreePub> phylotreePubs) {
       this.cvTerm = cvTerm;
       this.dbXRef = dbXRef;
       this.name = name;
       this.comment = comment;
       this.phylonodes = phylonodes;
       this.phylotreePubs = phylotreePubs;
    }
   
    // Property accessors
     @Id
    @Column(name="phylotree_id", unique=true, nullable=false, insertable=true, updatable=true)
    public int getPhylotreeId() {
        return this.phylotreeId;
    }
    
    private void setPhylotreeId(int phylotreeId) {
        this.phylotreeId = phylotreeId;
    }
    
    @ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", unique=false, nullable=true, insertable=true, updatable=true)
    public CvTerm getCvTerm() {
        return this.cvTerm;
    }
    
    public void setCvTerm(CvTerm cvTerm) {
        this.cvTerm = cvTerm;
    }
    
    @ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="dbxref_id", unique=false, nullable=false, insertable=true, updatable=true)
    public DbXRef getDbXRef() {
        return this.dbXRef;
    }
    
    public void setDbXRef(DbXRef dbXRef) {
        this.dbXRef = dbXRef;
    }
    
    @Column(name="name", unique=false, nullable=true, insertable=true, updatable=true)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="comment", unique=false, nullable=true, insertable=true, updatable=true)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="phylotree")
    public Collection<Phylonode> getPhylonodes() {
        return this.phylonodes;
    }
    
    public void setPhylonodes(Set<Phylonode> phylonodes) {
        this.phylonodes = phylonodes;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="phylotree")
    public Collection<PhylotreePub> getPhylotreePubs() {
        return this.phylotreePubs;
    }
    
    public void setPhylotreePubs(Set<PhylotreePub> phylotreePubs) {
        this.phylotreePubs = phylotreePubs;
    }




}


