package org.gmod.schema.phylogeny;
// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7


import org.gmod.schema.cv.CvTerm;
import org.gmod.schema.general.DbXRef;

import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phylotree generated by hbm2java
 */
@Entity
@Table(name="phylotree", uniqueConstraints = {  })
public class Phylotree  implements java.io.Serializable {

    // Fields

     private int phylotreeId;
     private CvTerm cvTerm;
     private DbXRef dbXRef;
     private String name;
     private String comment;
     private Collection<Phylonode> phylonodes;
     private Collection<PhylotreePub> phylotreePubs;

     // Constructors

    /** default constructor */
    private Phylotree() {
        // Deliberately empty default constructor
    }

    /** minimal constructor */
    private Phylotree(DbXRef dbXRef) {
        this.dbXRef = dbXRef;
    }
    /** full constructor */
    private Phylotree(CvTerm cvTerm, DbXRef dbXRef, String name, String comment, Collection<Phylonode> phylonodes, Collection<PhylotreePub> phylotreePubs) {
       this.cvTerm = cvTerm;
       this.dbXRef = dbXRef;
       this.name = name;
       this.comment = comment;
       this.phylonodes = phylonodes;
       this.phylotreePubs = phylotreePubs;
    }

    // Property accessors
     @Id
    @Column(name="phylotree_id", unique=true, nullable=false, insertable=true, updatable=true)
    private int getPhylotreeId() {
        return this.phylotreeId;
    }

    private void setPhylotreeId(int phylotreeId) {
        this.phylotreeId = phylotreeId;
    }

    @ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", unique=false, nullable=true, insertable=true, updatable=true)
    private CvTerm getCvTerm() {
        return this.cvTerm;
    }

    private void setCvTerm(CvTerm cvTerm) {
        this.cvTerm = cvTerm;
    }

    @ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="dbxref_id", unique=false, nullable=false, insertable=true, updatable=true)
    private DbXRef getDbXRef() {
        return this.dbXRef;
    }

    private void setDbXRef(DbXRef dbXRef) {
        this.dbXRef = dbXRef;
    }

    @Column(name="name", unique=false, nullable=true, insertable=true, updatable=true)
    private String getName() {
        return this.name;
    }

    private void setName(String name) {
        this.name = name;
    }

    @Column(name="comment", unique=false, nullable=true, insertable=true, updatable=true)
    private String getComment() {
        return this.comment;
    }

    private void setComment(String comment) {
        this.comment = comment;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="phylotree")
    private Collection<Phylonode> getPhylonodes() {
        return this.phylonodes;
    }

    private void setPhylonodes(Collection<Phylonode> phylonodes) {
        this.phylonodes = phylonodes;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="phylotree")
    private Collection<PhylotreePub> getPhylotreePubs() {
        return this.phylotreePubs;
    }

    private void setPhylotreePubs(Collection<PhylotreePub> phylotreePubs) {
        this.phylotreePubs = phylotreePubs;
    }




}


