package org.gmod.schema.phylogeny;
// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7


import org.gmod.schema.pub.Pub;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PhylonodePub generated by hbm2java
 */
@Entity
@Table(name="phylonode_pub"
    ,schema="public"
    , uniqueConstraints = { @UniqueConstraint( columnNames = { "phylonode_id", "pub_id" } ) }
)
public class PhylonodePub  implements java.io.Serializable {

    // Fields    

     private int phylonodePubId;
     private Pub pub;
     private Phylonode phylonode;

     // Constructors

    /** default constructor */
    public PhylonodePub() {
    }

    /** full constructor */
    public PhylonodePub(int phylonodePubId, Pub pub, Phylonode phylonode) {
       this.phylonodePubId = phylonodePubId;
       this.pub = pub;
       this.phylonode = phylonode;
    }
   
    // Property accessors
     @Id
    
    @Column(name="phylonode_pub_id", unique=true, nullable=false, insertable=true, updatable=true)
    public int getPhylonodePubId() {
        return this.phylonodePubId;
    }
    
    public void setPhylonodePubId(int phylonodePubId) {
        this.phylonodePubId = phylonodePubId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="pub_id", unique=false, nullable=false, insertable=true, updatable=true)
    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="phylonode_id", unique=false, nullable=false, insertable=true, updatable=true)
    public Phylonode getPhylonode() {
        return this.phylonode;
    }
    
    public void setPhylonode(Phylonode phylonode) {
        this.phylonode = phylonode;
    }




}


