<div id="homepage-text">
 <a name="The_Disease">
 </a>
 <h2>
  <span class="mw-headline">
   The Disease
  </span>
 </h2>
 <p>
  Protozoan parasites within the species
  <i>
   Trypanosoma cruzi
  </i>
  are responsible for New World Trypanosomiasis or Chaga's disease. Chaga's disease is endemic throughout South America and Latin America and is transmitted between animal hosts through reduviid bug vectors. Chaga's disease manifests itself in a wide range of both acute and chronic symptoms, causing damage to the nervous system, digestive system and circulatory system. Untreated Chaga's disease frequently results in death from heart failure.
 </p>
 <p>
  Further information can be found on the
  <a href="http://www.who.int/health_topics/leishmaniasis/en/" class="external text" title="http://www.who.int/health_topics/leishmaniasis/en/" rel="nofollow">
   World Health Organization web site
  </a>
  .
 </p>
 <a name="The_Genome">
 </a>
 <h2>
  <span class="mw-headline">
   The Genome
  </span>
 </h2>
 <p>
  The nuclear genome of Trypanosoma cruzi CL Brener is being sequenced by the TIGR-Seattle Biomedical Research Institute-Karolinska Institute
  <i>
   T. cruzi
  </i>
  Sequencing Consortium (TSK-TSC). Funding for this project is being provided by the National Institute of Allergy and Infectious Diseases (NIAID). This is the fourth release (v 4.0) of the
  <i>
   Trypanosoma cruzi
  </i>
  genome sequence, gene predictions and annotation generated by the TSK-TSC. Contig sequences have *not changed* since the previous release, with the exception of 6 contigs that were removed from this new dataset, since they correspond to bacterial contamination. The
  <i>
   T. cruzi
  </i>
  release v4.0 consists of 4,008 annotated contigs totaling 60.4 Mb, plus a further 28737 unannotated contigs totalling 29.2 Mb. The 23,216 gene models were initially annotated through a system that executes multiple steps of homology search and then determines the best call based on multiple sources of evidence. In a next step, a more refined gene function prediction was implemented by a combination of manual curation of T. cruzi specific genes as well as transfer of manual curation of gene products from their
  <i>
   T. brucei
  </i>
  or
  <i>
   L. major
  </i>
  orthologs.
 </p>
 <a name="The_Database">
 </a>
 <h2>
  <span class="mw-headline">
   The Database
  </span>
 </h2>
 <p>
  GeneDB has been funded by Wellcome Trust to provide full curation support for kinetoplastida genomes to meet the needs of the community.
  <b>
  </b>
  New annotations are constantly being added to keep up with published manuscripts and feedback from the Trypanosomatid research community. In collaboration with GeneDB, the EuPathDB genomic sequence data and annotations are regularly deposited on
  <a href="http://tritrypdb.org/tritrypdb/" class="external text" title="http://tritrypdb.org/tritrypdb/" rel="nofollow">
   <b>
    TriTrypDB
   </b>
  </a>
  where they can be integrated with other datasets and queried using customized queries.
 </p>
 <a name="Data_Release">
 </a>
 <h2>
  <span class="mw-headline">
   Data Release
  </span>
 </h2>
 <p>
  This annotated genome sequence has been published in El-Sayed et al.2005, Science 309(5733):409-415 and is available for use without restriction. However, the annotation is pro-actively updated and curated.If you find the this resource helpful in your research, acknowledging the project in your publications will help insure its longevity.
 </p>
</div>