package org.genedb.web.mvc.controller.download;

public enum OutputOption {
	ORGANISM, SYS_ID, PRIMARY_NAME, PRODUCT, SYNONYMS, 
	PREV_SYS_ID, CHROMOSOME, LOCATION, EC_NUMBERS, 
	NUM_TM_DOMAINS, SIG_P, GPI_ANCHOR, MOL_WEIGHT, 
	ISOELECTRIC_POINT, GO_IDS, PFAM_IDS, INTERPRO_IDS,
    
    
    SEQ_PROTEIN, SEQ_UNSPLICED, SEQ_SPLICED, SEQ_5P_UTR, 
    SEQ_3P_UTR, SEQ_5P_INTERGENIC, SEQUENCE_3P_INTERGENIC, 
    SEQ_INTERGENIC, SEQ_INTRON;
}
