<p>The most recent sequence updates and annotations for the<i> L. braziliensis</i> genome can be found in <a href="http://www.genedb.org/genedb/leish/">GeneDB</a>.</p>
<p><b></b><br></p>
<p><b>The disease</b></p>
<p>The <i>Leishmania</i> parasite is an intracellular pathogen of the immune system targeting macrophages and dendritic cells. The disease Leishmaniasis affects the populations of 88 counties worldwide with symptoms ranging from disfiguring cutaneous and muco-cutaneous lesions that can cause widespread destruction of mucous membranes to visceral disease affecting the haemopoetic organs.</p>
<p><i>Leishmania braziliensis</i>is the third <i>Leishmania</i> species to be sequenced at the Wellcome Trust Sanger Institute. Unlike previous species sequenced, it is a New World pathogen that is endemic throughout South America and currently the only <i>Leishmania</i> genome from the Viannia species group. As well as causing localised cutaneous lesions in affected people, <i>Leishmania braziliensis</i> can also result in a more destructive, progressive infection in mucosal tissue in a proportion of patients. This can lead to chronic destruction of the nasel septum and soft palate. Karyotyping of <i>Leishmania braziliensis</i> has shown that it has 35 chromosomes compared to the 36 present in old world species. The difference in chromosome number is due to the fusion of chromosomes 20 and 34 to make a single chromosome in <i>Leishmania braziliensis</i>.</p>
<p><b>The Genome</b></p>
<p>We have generated a whole genome shotgun, to approximately 5x coverage, of <i>Leishmania braziliensis</i> clone MHOM/BR/75M2904. This project is a collaboration with <a href="mailto:akcruz@fmrp.usp.br"></a> (Universidade de São Paulo - FMRP - USP) and <a href="mailto:dfs501@york.ac.uk">Debbie Smith</a> (Imperial College).</p>
<p><b>The Database</b></p>
<p>GeneDB has been funded by Wellcome Trust to provide full curation support for kinetoplastida genomes to meet the needs of the community.<b> </b>New annotations are constantly being added to keep up with published manuscripts and feedback from the Trypanosomatid research community. In collaboration with GeneDB, the EuPathDB genomic sequence data and annotations are regularly deposited on <a href="http://tritrypdb.org/tritrypdb/"><b>TriTrypDB</b></a> where they can be integrated with other datasets and queried using customized queries.</p>
<p><b>Downloads</b></p>
<p>As soon as they are produced, the most up to date <i>L. braziliensis</i> annotations are always available at GeneDB. However, we recommend TriTrypDB as the portal for sequence download, where the date are periodically released with version numbers for consistent cross-referencing in publications.</p>
<p><b>Data Release</b></p>
<p>The genome is now published as part of a comparative genome analysis with <i>L. major</i> and <i>L. infantum</i> in Peacock et al, Nature Genetics, 39 839-847<i> </i> and is available for use without restriction. However, the annotation is pro-actively updated and curated. If you find the this resource helpful in your research, acknowledging the project in your publications will help insure its longevity.</p>
<p><b>Sequencing Enquiries</b></p>
<p>Please address all sequencing enquiries to Dr. Matthew Rogers (email: mr7@sanger.ac.uk).</p>
<p></p>