<p>The most recent sequence updates and annotations for the<i> L. infantum</i> genome can be found in <a href="http://www.genedb.org/genedb/leish/"><span class="s1">GeneDB</span></a><span class="s1">.</span></p>
<p><b></b><br></p>
<p><b>The disease</b></p>
<p>The <i>Leishmania</i> parasite is an intracellular pathogen of the immune system targeting macrophages and dendritic cells. The disease Leishmaniasis affects the populations of 88 counties worldwide with symptoms ranging from disfiguring cutaneous and muco-cutaneous lesions that can cause widespread destruction of mucous membranes to visceral disease affecting the haemopoetic organs.</p>
<p>Severe and life-threatening visceral leishmaniasis is caused by <i>L. donovani</i> species. It is endemic in 62 countries with a total of 200 million cases people at risk, an estimated 0.5 million new cases worldwide each year and 41,000 recorded deaths in 2000. More than 90% of cases occur in Bangladesh, Brazil, India and Sudan. However the number of human cases in Southern Europe has also risen dramatically in recent years due to Leishmania/HIV coinfection. The WHO(TDR) recently carried out an analysis on the burden of disease caused by the 10 most neglected tropical diseases, ones that represent major public health problems in developing countries (see <a href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12377584&amp;dopt=Abstract"><span class="s1">review</span></a>).</p>
<p>The species of the <i>L. donovani</i> complex are found in different geographical regions. <i>L. donovani</i> is the primary cause of visceral leishmaniasis in the Indian subcontinent and East Africa, <i>L. infantum</i> in the the Mediterranean region and <i>L. chagasi</i> in the New World. While the last two species are genetically identical, all three species are very similar. <i>L. infantum</i> has been chosen as the next <i>Leishmania</i> species to sequence after <i>L. major</i> because it is part of the <i>L. donovani</i> complex and is an adaptable species for experimentation.</p>
<p><b>The genome</b></p>
<p>We have generated a whole genome shotgun, to ~5x coverage, of L. infantum clone JPCM5 (MCAN/ES/98/LLM-877). This was completed in October 2003. This project is a collaboration with <a href="mailto:dfs501@york.ac.uk">Professor Debbie Smith</a> (Imperial College) and <a href="mailto:gbga18@udcf.gla.ac.uk">Professor Jeremy Mottram</a> (University of Glasgow).</p>
<p><b>The Database</b></p>
<p>GeneDB has been funded by Wellcome Trust to provide full curation support for kinetoplastida genomes to meet the needs of the community.<b> </b>New annotations are constantly being added to keep up with published manuscripts and feedback from the Trypanosomatid research community. In collaboration with GeneDB, the EuPathDB genomic sequence data and annotations are regularly deposited on <a href="http://tritrypdb.org/tritrypdb/"><b>TriTrypDB</b></a> where they can be integrated with other datasets and queried using customized queries.</p>
<p><b>Downloads</b></p>
<p>As soon as they are produced, the most up to date <i>L. infantum</i> annotations are always available at GeneDB. However, we recommend TriTrypDB as the portal for sequence download, where the date are periodically released with version numbers for consistent cross-referencing in publications.</p>
<p><b>Data Release</b></p>
<p>The genome is now published as part of a comparative genome analysis with <i>L. major</i> and <i>L. braziliensi</i>s in Peacock <i>et al</i>, Nature Genetics, <b>39</b> 839-847 and is available for use without restriction.<span class="Apple-converted-space">  </span>However, the annotation is pro-actively updated and curated. If you find the this resource helpful in your research, acknowledging the project in your publications will help insure its longevity.</p>
<p><b>Sequencing Enquiries</b></p>
<p>Please address all sequencing enquiries to Dr. Matthew Rogers (email: mr7@sanger.ac.uk).</p>
<p></p>