<div id="homepage-text">
 <a name="The_Genome">
 </a>
 <h2>
  <span class="mw-headline">
   The Genome
  </span>
 </h2>
 <p>
  <i>
   Eimeria tenella
  </i>
  is an apicomplexan intracellular coccidial parasite of the chicken. It is estimated to have a genome size of ~60Mb.
 </p>
 <p>
  At present two data sets for for the Houghton strain of E. tenella are available through GeneDB generated by the E. tenella genome project at
  <a href="http://www.sanger.ac.uk/Projects/E_tenella/" class="external text" title="http://www.sanger.ac.uk/Projects/E_tenella/" rel="nofollow">
   The Wellcome Trust Sanger Institute
  </a>
  and the E. tenella chromosome 1 project at the [http:/genome.ukm.my/ Malaysia Genome Institute]. For background information please click here.
 </p>
 <p>
  <br />
 </p>
 <a name="The_Database">
 </a>
 <h2>
  <span class="mw-headline">
   The Database
  </span>
 </h2>
 <p>
  The consortium plans on publishing the completed and annotated sequences in a peer-reviewed journal as soon as possible. Permission of the principal investigators should be obtained before publishing analyses of the sequence/open reading frames/genes on a chromosome or genome scale.
 </p>
</div>