package org.gmod.schema.phylogeny;
// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7


import org.gmod.schema.organism.Organism;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PhylonodeOrganism generated by hbm2java
 */
@Entity
@Table(name="phylonode_organism", uniqueConstraints = { @UniqueConstraint( columnNames = { "phylonode_id" } ) })
public class PhylonodeOrganism  implements java.io.Serializable {

    // Fields    

     private int phylonodeOrganismId;
     private Organism organism;
     private Phylonode phylonode;

     // Constructors

    /** default constructor */
    public PhylonodeOrganism() {
    }

    /** full constructor */
    public PhylonodeOrganism(int phylonodeOrganismId, Organism organism, Phylonode phylonode) {
       this.phylonodeOrganismId = phylonodeOrganismId;
       this.organism = organism;
       this.phylonode = phylonode;
    }
   
    // Property accessors
     @Id
    
    @Column(name="phylonode_organism_id", unique=true, nullable=false, insertable=true, updatable=true)
    public int getPhylonodeOrganismId() {
        return this.phylonodeOrganismId;
    }
    
    public void setPhylonodeOrganismId(int phylonodeOrganismId) {
        this.phylonodeOrganismId = phylonodeOrganismId;
    }
    
@ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="organism_id", unique=false, nullable=false, insertable=true, updatable=true)
    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }
    
@ManyToOne(cascade={}, fetch=FetchType.LAZY)
    @JoinColumn(name="phylonode_id", unique=true, nullable=false, insertable=true, updatable=true)
    public Phylonode getPhylonode() {
        return this.phylonode;
    }
    
    public void setPhylonode(Phylonode phylonode) {
        this.phylonode = phylonode;
    }




}


