package org.genedb.querying.tmpquery;

import org.genedb.querying.core.HqlQuery;
import org.genedb.querying.core.QueryClass;
import org.genedb.querying.core.QueryParam;

@QueryClass(
        title="Coding and pseudogenes by their annotation status",
        shortDesc="Genes by annotation status",
        longDesc=""
    )
public class AnnotationStatusQuery extends HqlQuery {

    @QueryParam(
            order=1,
            title="Include automatic genes"
    )
    private boolean automatic = false;

    @Override
    protected String getHql() {
        return "select f.uniqueName from Feature f where f.annotation = :automatic";
    }

    // ------ Autogenerated code below here

    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }

    public boolean getAutomatic() {
        return automatic;
    }

    @Override
    protected String[] getParamNames() {
        return new String[] {"automatic"};
    }

    @Override
    protected void populateQueryWithParams(org.hibernate.Query query) {
        query.setBoolean("automatic", automatic);
    }





}
