package org.genedb.querying.tmpquery;

import org.genedb.querying.core.HqlQuery;
import org.genedb.querying.core.QueryClass;
import org.genedb.querying.core.QueryParam;

import java.util.HashMap;
import java.util.Map;

@QueryClass(
        title="Transcripts by their type",
        shortDesc="Get a list of transcripts by type",
        longDesc=""
    )
public class ControlledCurationQuery extends HqlQuery {

    @QueryParam(
            order=1,
            title="Name of CV"
    )
    private String cvName;


    @QueryParam(
            order=2,
            title="Name of CV term"
    )
    private String cvTermName;

    @Override
    protected String getHql() {
        return "select f.uniqueName from Feature f, FeatureCvTerm fct where fct.feature=f and fct.cvTerm.name=:cvTermName and fct.cvTerm.cv.name=:cvName";
    }


//    public Map<String, Object> prepareModelData() {
//        Map<String, String> typeMap = new HashMap<String, String>();
//        typeMap.put("mRNA", "protein-coding");
//        typeMap.put("pseudogene", "pseudogenic transcript");
//        typeMap.put("tRNA", "tRNA");
//        typeMap.put("snoRNA", "snoRNA");
//
//        Map<String, Object> ret = new HashMap<String, Object>();
//        ret.put("typeMap", typeMap);
//        return ret;
//    }

    // ------ Autogenerated code below here

    public String getCvName() {
        return cvName;
    }


    public void setCvName(String cvName) {
        this.cvName = cvName;
    }


    public String getCvTermName() {
        return cvTermName;
    }


    public void setCvTermName(String cvTermName) {
        this.cvTermName = cvTermName;
    }

    @Override
    protected String[] getParamNames() {
        return new String[] {"cvName", "cvTermName"};
    }

    @Override
    protected void populateQueryWithParams(org.hibernate.Query query) {
        query.setString("cvName", cvName);
        query.setString("cvTermName", cvTermName);
    }

}
