package org.genedb.querying.tmpquery;

import org.genedb.querying.core.QueryClass;
import org.genedb.querying.core.QueryParam;

import java.util.Date;

@QueryClass(
        title="Transcripts by their type",
        shortDesc="Get a list of transcripts by type",
        longDesc=""
    )
public class DateQuery extends OrganismHqlQuery {

    @QueryParam(
            order=1,
            title="Date of modification"
    )
    private Date date;


    @QueryParam(
            order=2,
            title="After this date"
    )
    private boolean after;

    @QueryParam(
            order=3,
            title="Just look at creation date"
    )
    private boolean created;


    @Override
    protected String getHql() {
        System.err.println("date in hql is '"+date+"'");
        String operator = after ? ">" : "<";
        String typeOfDate = created ? "timeAccessioned" : "timeLastModified";
        return String.format("select f.uniqueName from Feature f where f.%s %s :date order by f.organism", typeOfDate, operator);
    }

    @Override
    protected String getOrganismHql() {
        // TODO Auto-generated method stub
        return null;
    }

    // ------ Autogenerated code below here

    public Date getDate() {
        return date;
    }


    public void setDate(Date date) {
        System.err.println("date in setter is '"+date+"'");
        this.date = date;
    }


    public boolean isCreated() {
        return created;
    }


    public void setCreated(boolean created) {
        this.created = created;
    }


    public boolean isAfter() {
        return after;
    }

    public void setAfter(boolean after) {
        this.after = after;
    }

    @Override
    protected String[] getParamNames() {
        return new String[] {"date", "created", "after"};
    }

    @Override
    protected void populateQueryWithParams(org.hibernate.Query query) {
        query.setDate("date", date);
    }

}
