-- Autogenerated on Fri May  8 09:41:59 2009 by mkaudit.pl

create table audit.cvterm_dbxref (
    dbxref_id integer not null
  , cvterm_dbxref_id integer not null
  , cvterm_id integer not null
  , is_for_definition integer not null
) inherits (audit.audit);

create or replace function audit.audit_cvterm_dbxref_insert_proc()
returns trigger
as $$
BEGIN
  raise exception 'Cannot insert directly into audit.cvterm_dbxref. Use one of the child tables.';
END;
$$ language plpgsql;
create trigger cvterm_dbxref_insert_tr before insert on audit.cvterm_dbxref
    for each statement execute procedure audit.audit_cvterm_dbxref_insert_proc();
grant select on audit.cvterm_dbxref to chado_ro_role;
grant select, insert on audit.cvterm_dbxref to chado_rw_role;
grant execute on function audit.audit_cvterm_dbxref_insert_proc() to chado_rw_role;


create table audit.cvterm_dbxref_insert (
    constraint cvterm_dbxref_insert_ck check (type = 'INSERT')
) inherits (audit.cvterm_dbxref);
alter table audit.cvterm_dbxref_insert alter type set default 'INSERT';
grant select on audit.cvterm_dbxref_insert to chado_ro_role;
grant select, insert on audit.cvterm_dbxref_insert to chado_rw_role;

create or replace function audit.public_cvterm_dbxref_insert_proc()
returns trigger
as $$
BEGIN
  insert into audit.cvterm_dbxref_insert (
      cvterm_dbxref_id, cvterm_id, dbxref_id, is_for_definition
  ) values (
      new.cvterm_dbxref_id, new.cvterm_id, new.dbxref_id, new.is_for_definition
  );
  return new;
END;
$$ language plpgsql;
create trigger cvterm_dbxref_audit_insert_tr after insert on public.cvterm_dbxref
    for each row execute procedure audit.public_cvterm_dbxref_insert_proc();
grant execute on function audit.public_cvterm_dbxref_insert_proc() to chado_rw_role;


create table audit.cvterm_dbxref_update (
    constraint cvterm_dbxref_update_ck check (type = 'UPDATE')
  , old_cvterm_id integer not null
  , old_is_for_definition integer not null
  , old_dbxref_id integer not null
) inherits (audit.cvterm_dbxref);
alter table audit.cvterm_dbxref_update alter type set default 'UPDATE';
grant select on audit.cvterm_dbxref_update to chado_ro_role;
grant select, insert on audit.cvterm_dbxref_update to chado_rw_role;

create or replace function audit.public_cvterm_dbxref_update_proc()
returns trigger
as $$
BEGIN
  if old.cvterm_dbxref_id <> new.cvterm_dbxref_id or old.cvterm_dbxref_id is null <> new.cvterm_dbxref_id is null then
    raise exception 'If you want to change cvterm_dbxref.cvterm_dbxref_id (do you really?) then disable the audit trigger cvterm_dbxref_audit_update_tr';
  end if;
  insert into audit.cvterm_dbxref_update (
      cvterm_dbxref_id, cvterm_id, dbxref_id, is_for_definition,
      old_cvterm_id, old_dbxref_id, old_is_for_definition
   ) values (
       new.cvterm_dbxref_id, new.cvterm_id, new.dbxref_id, new.is_for_definition,
       old.cvterm_id, old.dbxref_id, old.is_for_definition
   );
  return new;
END;
$$ language plpgsql;
create trigger cvterm_dbxref_audit_update_tr after update on public.cvterm_dbxref
    for each row execute procedure audit.public_cvterm_dbxref_update_proc();
grant execute on function audit.public_cvterm_dbxref_update_proc() to chado_rw_role;


create table audit.cvterm_dbxref_delete (
    constraint cvterm_dbxref_delete_ck check (type = 'DELETE')
) inherits (audit.cvterm_dbxref);
alter table audit.cvterm_dbxref_delete alter type set default 'DELETE';
grant select on audit.cvterm_dbxref_delete to chado_ro_role;
grant select, insert on audit.cvterm_dbxref_delete to chado_rw_role;

create or replace function audit.public_cvterm_dbxref_delete_proc()
returns trigger
as $$
BEGIN
  insert into audit.cvterm_dbxref_delete (
      cvterm_dbxref_id, cvterm_id, dbxref_id, is_for_definition
  ) values (
      old.cvterm_dbxref_id, old.cvterm_id, old.dbxref_id, old.is_for_definition
  );
  return old;
END;
$$ language plpgsql;
create trigger cvterm_dbxref_audit_delete_tr after delete on public.cvterm_dbxref
    for each row execute procedure audit.public_cvterm_dbxref_delete_proc();
grant execute on function audit.public_cvterm_dbxref_delete_proc() to chado_rw_role;
