package org.genedb.querying.tmpquery;

import org.genedb.querying.core.QueryClass;
import org.genedb.querying.core.QueryParam;

@QueryClass(
        title="Coding and pseudogenes by their annotation status",
        shortDesc="Genes by annotation status",
        longDesc=""
    )
public class AnnotationStatusQuery extends OrganismHqlQuery {

    @QueryParam(
            order=1,
            title="Include automatic genes"
    )
    private boolean automatic = false;
    
    @Override
    public String getQueryDescription() {
    	return "Search by annotation status.";
    }
    
    @Override
    public String getQueryName() {
        return "Annotation Status";
    }
    
    @Override
    protected String getHql() {
        return "select @SELECTOR@ from Feature f where f.annotation = :automatic ";
    }

    @Override
    protected String getOrganismHql() {
        // TODO Auto-generated method stub
        return null;
    }

    // ------ Autogenerated code below here

    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }

    public boolean getAutomatic() {
        return automatic;
    }

    @Override
    protected String[] getParamNames() {
        return new String[] {"automatic"};
    }

    @Override
    protected void populateQueryWithParams(org.hibernate.Query query) {
        query.setBoolean("automatic", automatic);
    }

	

	@Override
	protected String getOrderBy() {
		return " order by f.organism ";
	}
    
    

}
