-- Autogenerated on Fri May  8 09:42:01 2009 by mkaudit.pl

create table audit.pub_dbxref (
    dbxref_id integer not null
  , is_current boolean not null
  , pub_id integer not null
  , pub_dbxref_id integer not null
) inherits (audit.audit);

create or replace function audit.audit_pub_dbxref_insert_proc()
returns trigger
as $$
BEGIN
  raise exception 'Cannot insert directly into audit.pub_dbxref. Use one of the child tables.';
END;
$$ language plpgsql;
create trigger pub_dbxref_insert_tr before insert on audit.pub_dbxref
    for each statement execute procedure audit.audit_pub_dbxref_insert_proc();
grant select on audit.pub_dbxref to chado_ro_role;
grant select, insert on audit.pub_dbxref to chado_rw_role;
grant execute on function audit.audit_pub_dbxref_insert_proc() to chado_rw_role;


create table audit.pub_dbxref_insert (
    constraint pub_dbxref_insert_ck check (type = 'INSERT')
) inherits (audit.pub_dbxref);
alter table audit.pub_dbxref_insert alter type set default 'INSERT';
grant select on audit.pub_dbxref_insert to chado_ro_role;
grant select, insert on audit.pub_dbxref_insert to chado_rw_role;

create or replace function audit.public_pub_dbxref_insert_proc()
returns trigger
as $$
BEGIN
  insert into audit.pub_dbxref_insert (
      pub_dbxref_id, pub_id, dbxref_id, is_current
  ) values (
      new.pub_dbxref_id, new.pub_id, new.dbxref_id, new.is_current
  );
  return new;
END;
$$ language plpgsql;
create trigger pub_dbxref_audit_insert_tr after insert on public.pub_dbxref
    for each row execute procedure audit.public_pub_dbxref_insert_proc();
grant execute on function audit.public_pub_dbxref_insert_proc() to chado_rw_role;


create table audit.pub_dbxref_update (
    constraint pub_dbxref_update_ck check (type = 'UPDATE')
  , old_dbxref_id integer not null
  , old_is_current boolean not null
  , old_pub_id integer not null
) inherits (audit.pub_dbxref);
alter table audit.pub_dbxref_update alter type set default 'UPDATE';
grant select on audit.pub_dbxref_update to chado_ro_role;
grant select, insert on audit.pub_dbxref_update to chado_rw_role;

create or replace function audit.public_pub_dbxref_update_proc()
returns trigger
as $$
BEGIN
  if old.pub_dbxref_id <> new.pub_dbxref_id or old.pub_dbxref_id is null <> new.pub_dbxref_id is null then
    raise exception 'If you want to change pub_dbxref.pub_dbxref_id (do you really?) then disable the audit trigger pub_dbxref_audit_update_tr';
  end if;
  insert into audit.pub_dbxref_update (
      pub_dbxref_id, pub_id, dbxref_id, is_current,
      old_pub_id, old_dbxref_id, old_is_current
   ) values (
       new.pub_dbxref_id, new.pub_id, new.dbxref_id, new.is_current,
       old.pub_id, old.dbxref_id, old.is_current
   );
  return new;
END;
$$ language plpgsql;
create trigger pub_dbxref_audit_update_tr after update on public.pub_dbxref
    for each row execute procedure audit.public_pub_dbxref_update_proc();
grant execute on function audit.public_pub_dbxref_update_proc() to chado_rw_role;


create table audit.pub_dbxref_delete (
    constraint pub_dbxref_delete_ck check (type = 'DELETE')
) inherits (audit.pub_dbxref);
alter table audit.pub_dbxref_delete alter type set default 'DELETE';
grant select on audit.pub_dbxref_delete to chado_ro_role;
grant select, insert on audit.pub_dbxref_delete to chado_rw_role;

create or replace function audit.public_pub_dbxref_delete_proc()
returns trigger
as $$
BEGIN
  insert into audit.pub_dbxref_delete (
      pub_dbxref_id, pub_id, dbxref_id, is_current
  ) values (
      old.pub_dbxref_id, old.pub_id, old.dbxref_id, old.is_current
  );
  return old;
END;
$$ language plpgsql;
create trigger pub_dbxref_audit_delete_tr after delete on public.pub_dbxref
    for each row execute procedure audit.public_pub_dbxref_delete_proc();
grant execute on function audit.public_pub_dbxref_delete_proc() to chado_rw_role;
