#!/bin/bash

shopt -s nullglob
set -e

# You can explicitly set GENEDB_HOME in the environment, for testing
if [ -z "$GENEDB_HOME" ]; then
    GENEDB_HOME="/software/pathogen/projects/genedb"
fi

if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME="/software/pathogen/external/applications/java/java6"
fi

export CLASSPATH=''
for jar in "$GENEDB_HOME/lib"/*.jar; do
    if [ -n "$CLASSPATH" ]; then
        CLASSPATH="$CLASSPATH:$jar"
    else
        CLASSPATH="$jar"
    fi
done

# readdir(array, dir, extension)
readdir() {
    array="$1"; dir="$2"; extension="$3"
    
    pushd >/dev/null "$dir"
    local -a files=(*.$extension)
    popd >/dev/null
    eval "${array}=(\"\${files[@]}\")"
}

readdir loaders "$GENEDB_HOME/bin/loaders" sh

print_help() {
    echo >&2
    echo >&2 "Usage: `basename $0` <loader> [options] <file or directory>"
    echo >&2
    echo >&2 "For help with a loader: `basename $0` <loader> -h"
    echo >&2 "(or `basename $0` <loader> -u to just print the usage summary)"
    echo >&2
    echo >&2 "The available loaders are:"
    for loading_script in "${loaders[@]}"; do
        echo >&2 -ne "\t${loading_script%.sh} - "
        source "$GENEDB_HOME/bin/loaders/$loading_script"
        >&2 summary
    done
    echo >&2
}

if [ $# -lt 1 ]; then
    print_help
    exit 1
fi


loader="$1"; shift
if [ ! -e "$GENEDB_HOME/bin/loaders/$loader.sh" ]; then
    echo >&2 "`basename $0`: No such loader '$loader'"
    exit 2
fi
source "$GENEDB_HOME/bin/loaders/$loader.sh"

if [ $# -lt 1 ]; then
    loaderUsage
    exit 1
fi

case "$1" in
    -h)  echo "Help for the $loader loader"
        if [ -t 1 ]; then
            {
                loaderHelp
                loaderUsage
            } | ${PAGER:-less}
        else
            loaderHelp
            loaderUsage
        fi
        exit 0
        ;;
    -u)  loaderUsage
        exit 0
        ;;
esac

doLoad "$@"
