-- Autogenerated on Tue Mar 24 12:24:23 2009 by mkaudit.pl

drop schema audit cascade;
create schema audit;
create sequence audit.audit_seq;

create table audit.audit (
  audit_id   integer default nextval('audit.audit_seq' :: regclass) primary key
, type       character varying not null
, username   character varying not null default user
, time       timestamp without time zone not null default now()
);

\i audit_feature.sql
\i audit_feature_cvterm.sql
\i audit_feature_cvterm_dbxref.sql
\i audit_feature_cvterm_pub.sql
\i audit_feature_cvtermprop.sql
\i audit_feature_dbxref.sql
\i audit_feature_pub.sql
\i audit_featureprop.sql
\i audit_featureprop_pub.sql
\i audit_organism.sql
\i audit_organismprop.sql
