package org.genedb.querying.tmpquery;

import org.genedb.querying.core.QueryClass;
import org.genedb.querying.core.QueryParam;

import org.apache.lucene.index.Term;
import org.apache.lucene.search.BooleanQuery;
import org.apache.lucene.search.TermQuery;
import org.apache.lucene.search.WildcardQuery;
import org.apache.lucene.search.BooleanClause.Occur;
import org.springframework.util.StringUtils;

import java.util.List;

@QueryClass(
        title="Coding and pseudogenes by protein length",
        shortDesc="Get a list of transcripts ",
        longDesc=""
    )
public class CurationQuery extends OrganismLuceneQuery {

    @QueryParam(
            order=1,
            title="The search string"
    )
    private String search = "";


    @Override
    protected String getluceneIndexName() {
        return "org.gmod.schema.mapped.Feature";
    }
    
    @Override
    public String getQueryName() {
        return "Curation and Comments";
    }

    @Override
    protected void getQueryTermsWithoutOrganisms(List<org.apache.lucene.search.Query> queries) {

        BooleanQuery bq = new BooleanQuery();
        if(StringUtils.containsWhitespace(search)) {
        	BooleanQuery bq_sub = new BooleanQuery();
            for(String term : search.split(" ")) {
            	bq_sub.add(new TermQuery(new Term("allCuration",term.toLowerCase())), Occur.SHOULD);
            }
            bq.add(bq_sub, Occur.MUST);
        } else {
        	
            if (search.indexOf('*') == -1) {
            	bq.add(new TermQuery(new Term("allCuration",search.toLowerCase())), Occur.MUST);
            } else {
            	bq.add(new WildcardQuery(new Term("allCuration", search.toLowerCase())), Occur.MUST);
            }
            
        }
        
        // TODO determine the cvterm id programmatically
        bq.add(new TermQuery(new Term("type.cvTermId", "191")), Occur.MUST);
        
        queries.add(bq);
        //queries.add(productiveTranscriptQuery);

    }

    // ------ Autogenerated code below here

    public void setSearch(String search) {
        this.search = search;
    }

    public String getSearch() {
        return search;
    }

    @Override
    protected String[] getParamNames() {
        return new String[] {"search"};
    }
    
    @Override
    public String getQueryDescription() {
    	return "Searches curation and comments.";
    }

}
